import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';

/**
 * The service worker's configuration (ISC-329): what the shell is, and what it is not.
 *
 * <p>It reads `ngsw-config.json`, `angular.json` and `app.config.ts` from disk, because the
 * questions are about the files rather than about a running worker: does the `app` group
 * name every part of the shell, are the help assets and the fonts lazy, is there no data
 * group, is `/api/` kept out of the navigation fallback and out of every asset group, and is
 * the worker keyed on the build mode. A worker that cached one `/api/` response would show
 * yesterday's shortlist as today's with nothing in the UI to say so, and one that answered
 * the package download with the cached index would hand out an HTML file named like a
 * package; both are the failures this spec turns into a red line. The `enabled` clause is
 * held by a source read of `app.config.ts`, marked as such in the spec's report.
 *
 * <p>The worker itself (`ngsw-worker.js`, `ngsw.json`) is generated by the production build
 * from this file and the build output, and is checked by the lane's build step, not here.
 */

const FRONTEND = process.cwd();
const NGSW_CONFIG = resolve(FRONTEND, 'ngsw-config.json');
const ANGULAR_JSON = resolve(FRONTEND, 'angular.json');
const APP_CONFIG = resolve(FRONTEND, 'src/app/app.config.ts');

interface AssetGroup {
    name: string;
    installMode?: 'prefetch' | 'lazy';
    updateMode?: 'prefetch' | 'lazy';
    resources: {files?: string[]; urls?: string[]};
}

interface NgswConfig {
    $schema?: string;
    index: string;
    assetGroups: AssetGroup[];
    dataGroups?: unknown;
    navigationUrls?: string[];
}

interface BuildTarget {
    options: Record<string, unknown>;
    configurations: Record<string, Record<string, unknown>>;
}

describe('the service worker configuration (ISC-329)', () => {
    const text = readFileSync(NGSW_CONFIG, 'utf8');
    const config = JSON.parse(text) as NgswConfig;
    const group = (name: string): AssetGroup => {
        const found = config.assetGroups.find((g) => g.name === name);
        expect(found, `asset group "${name}"`).toBeDefined();
        return found!;
    };
    const files = (name: string): string[] => group(name).resources.files ?? [];

    it('names the index the worker serves for a navigation', () => {
        expect(config.index).toBe('/index.html');
    });

    it('prefetches the shell: the index, the manifest, the bundles and the styles', () => {
        const app = group('app');
        expect(app.installMode).toBe('prefetch');
        const shell = files('app');
        expect(shell).toContain('/index.html');
        expect(shell).toContain('/manifest.webmanifest');
        expect(shell).toContain('/*.js');
        expect(shell).toContain('/*.css');
    });

    it('prefetches the icons with the shell', () => {
        const shell = files('app');
        expect(shell).toContain('/favicon.ico');
        expect(shell).toContain('/*.png');
    });

    it('prefetches both i18n catalogs with the shell, so a language switch works offline', () => {
        const i18n = group('i18n');
        expect(i18n.installMode).toBe('prefetch');
        expect(files('i18n')).toEqual(['/i18n/*.json']);
    });

    it('takes the fonts as they are used and refreshes them with a new version', () => {
        // Lazy on purpose: the fontsource imports declare every subset (latin-ext, cyrillic,
        // vietnamese, symbols), 11 files and 336 KB, and the page requests only the ones its
        // text needs. Those are cached on first paint, which is before anyone goes offline.
        const fonts = group('fonts');
        expect(fonts.installMode).toBe('lazy');
        expect(fonts.updateMode).toBe('prefetch');
        expect(files('fonts')).toEqual(['/media/*.woff2']);
        expect(files('app').some((pattern) => /\.woff2?/.test(pattern)), 'a font in app').toBe(false);
    });

    it('takes the help chapters and diagrams lazily and refreshes them with a new version', () => {
        const help = group('help');
        expect(help.installMode).toBe('lazy');
        expect(help.updateMode).toBe('prefetch');
        expect(files('help')).toEqual(['/help/**']);
    });

    it('fetches from no origin but its own', () => {
        for (const g of config.assetGroups) expect(g.resources.urls, g.name).toBeUndefined();
    });

    it('has no data group, so no response from the API is ever served from cache', () => {
        expect(config.dataGroups).toBeUndefined();
        expect(text).not.toMatch(/dataGroups/);
    });

    it('excludes /api from the navigation fallback', () => {
        // The package download is a top-level navigation to an extension-less URL under
        // `/api/`; the default navigation rules would answer it with the cached index.html.
        expect(config.navigationUrls).toBeDefined();
        expect(config.navigationUrls).toContain('!/api/**');
        expect(config.navigationUrls).toContain('/**');
    });

    it('names /api once, as that exclusion, and nowhere in an asset group', () => {
        expect(JSON.stringify(config.assetGroups)).not.toMatch(/\/api/);
        expect(text.match(/\/api/g)).toHaveLength(1);
        expect(config.navigationUrls?.filter((url) => url.includes('/api'))).toEqual(['!/api/**']);
    });

    it('names no configured value', () => {
        expect(text).not.toMatch(/\$\{/);
        expect(text).not.toMatch(/https?:/i);
    });
});

describe('the build emits the worker in production only (ISC-329)', () => {
    const angular = JSON.parse(readFileSync(ANGULAR_JSON, 'utf8')) as {
        projects: {frontend: {architect: {build: BuildTarget}}};
    };
    const build = angular.projects.frontend.architect.build;

    it('names the configuration on the production build', () => {
        expect(build.configurations['production']?.['serviceWorker']).toBe('ngsw-config.json');
    });

    it('names it neither on the shared options nor on the development build', () => {
        expect(build.options['serviceWorker']).toBeUndefined();
        expect(build.configurations['development']?.['serviceWorker']).toBeUndefined();
    });
});

describe('the worker is registered by build mode, never by hostname (ISC-329)', () => {
    // A source read: the provider is a function call in `app.config.ts`, and what the spec
    // holds is the literal clause. A TestBed would need a fake `isDevMode`, and the clause
    // is what FE-PWA-04 in plan.md pins.
    const source = readFileSync(APP_CONFIG, 'utf8');
    const call = /provideServiceWorker\(\s*'ngsw-worker\.js'\s*,\s*\{([^}]*)\}\s*\)/.exec(source);
    const options = call?.[1] ?? '';

    it('registers ngsw-worker.js with enabled keyed on isDevMode', () => {
        expect(call, 'provideServiceWorker call').not.toBeNull();
        // The clause has to end at the comma or the brace: `!isDevMode() || true` must fail.
        expect(options).toMatch(/enabled:\s*!isDevMode\(\)\s*[,}]/);
        expect(options).toMatch(/registrationStrategy:\s*'registerWhenStable:30000'/);
    });

    it('never asks the hostname', () => {
        // Over the options clause, not the file: the comment above the call is allowed to
        // say why a hostname rule was rejected.
        expect(options).not.toMatch(/hostname|location|localhost/);
    });
});
