import {
  Archive,
  ArchiveRestore,
  ArchiveX,
  ArrowDown,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowUp,
  ArrowUpNarrowWide,
  Ban,
  BookOpen,
  Bookmark,
  Building2,
  CalendarDays,
  ChartLine,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  Clock,
  Columns3,
  Copy,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Funnel,
  GripVertical,
  Inbox,
  Keyboard,
  Layers,
  LayoutDashboard,
  ListChecks,
  ListFilter,
  MapPin,
  MessageCircleQuestionMark,
  Monitor,
  Package,
  Moon,
  RefreshCw,
  Rows2,
  Rows4,
  Scale,
  ScanSearch,
  Search,
  Send,
  Settings,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Trash2,
  TriangleAlert,
  CalendarArrowUp,
  CalendarClock,
  CircleDot,
  CircleX,
  Handshake,
  Hourglass,
  House,
  MessageSquareReply,
  Star,
  Tag,
  TrendingDown,
  TrendingUp,
  Trophy,
  Users,
  X,
  Maximize,
  ZoomIn,
  ZoomOut,
} from 'lucide';

/** Lucide 1.x hands out a flat `[tag, attributes][]`; there are no nested children. */
export type IconPart = readonly [string, Record<string, string | number | undefined>];
export type IconNode = readonly IconPart[];

/**
 * One named import per icon, because `lucide` is side-effect-free ESM and a named
 * import is the only shape esbuild can tree-shake — a wildcard would pull all
 * ~1600 icons into the bundle.
 *
 * `lucide-angular` would be the obvious choice and is not usable here: version
 * 1.0.0 pins `@angular/core` to `13.x - 21.x`, which excludes this repo's 22.
 * Everything Angular-facing therefore lives in `icon.ts`, and swapping back later
 * touches these two files and no template.
 */
export const LG_ICONS = {
    archive: Archive,
  'arrow-down': ArrowDown,
  'arrow-down-wide-narrow': ArrowDownWideNarrow,
    'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-up-narrow-wide': ArrowUpNarrowWide,
    'archive-restore': ArchiveRestore,
    'archive-x': ArchiveX,
    ban: Ban,
    'book-open': BookOpen,
  bookmark: Bookmark,
    'building-2': Building2,
    'calendar-days': CalendarDays,
    'chart-line': ChartLine,
    'chevron-down': ChevronDown,
    'chevron-up': ChevronUp,
    'chevron-right': ChevronRight,
    'circle-alert': CircleAlert,
    'circle-check': CircleCheck,
    'circle-help': CircleHelp,
    clock: Clock,
    'columns-3': Columns3,
    copy: Copy,
    database: Database,
    download: Download,
  ellipsis: Ellipsis,
  eye: Eye,
  'eye-off': EyeOff,
    'external-link': ExternalLink,
    'file-text': FileText,
    funnel: Funnel,
    'grip-vertical': GripVertical,
    inbox: Inbox,
    keyboard: Keyboard,
    layers: Layers,
    'layout-dashboard': LayoutDashboard,
    'list-checks': ListChecks,
    'list-filter': ListFilter,
    'map-pin': MapPin,
    'message-circle-question': MessageCircleQuestionMark,
    monitor: Monitor,
    package: Package,
    moon: Moon,
    refresh: RefreshCw,
  'rows-2': Rows2,
  'rows-4': Rows4,
    scale: Scale,
    'scan-search': ScanSearch,
    search: Search,
    send: Send,
    settings: Settings,
    'sliders-horizontal': SlidersHorizontal,
    sparkles: Sparkles,
    sun: Sun,
  'trash-2': Trash2,
    'triangle-alert': TriangleAlert,
    'calendar-arrow-up': CalendarArrowUp,
    'calendar-clock': CalendarClock,
    'circle-dot': CircleDot,
    'circle-x': CircleX,
    handshake: Handshake,
    hourglass: Hourglass,
    house: House,
    'message-square-reply': MessageSquareReply,
    star: Star,
    tag: Tag,
    'trending-down': TrendingDown,
    'trending-up': TrendingUp,
    trophy: Trophy,
    users: Users,
    x: X,
    maximize: Maximize,
    'zoom-in': ZoomIn,
    'zoom-out': ZoomOut,
} as const satisfies Record<string, IconNode>;

export type LgIconName = keyof typeof LG_ICONS;
